language: csharp
solution: HtmlToOpenXml.sln
dotnet: 3.1.301
mono: none
install:
  - dotnet restore HtmlToOpenXml.sln
script:
  - dotnet build /p:Configuration=Release HtmlToOpenXml.sln
  - dotnet test ./test/HtmlToOpenXml.Tests/HtmlToOpenXml.Tests.csproj