//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;table style=&quot;border-width: 0px; border-style: solid; width: 90%;&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;2&quot; align=&quot;center&quot;&gt;
        ///&lt;tbody&gt;
        ///    &lt;tr align=&quot;center&quot;&gt;
        ///        &lt;td&gt;&lt;span style=&quot;background-color: #ffffff;&quot;&gt;Reviewed by: ________________________________&lt;/span&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;span style=&quot;background-color: #ffffff;&quot;&gt;Acceptance: ________________________________&lt;/span&gt;&lt;/td&gt;
        ///    &lt;/tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advanced_Table {
            get {
                return ResourceManager.GetString("Advanced_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Heading 1&lt;/h1&gt;
        ///    &lt;h2&gt;Heading 2&lt;/h2&gt;
        ///    &lt;h3&gt;Heading 3&lt;/h3&gt;
        ///    &lt;h4&gt;Heading 4&lt;/h4&gt;
        ///    &lt;h5&gt;Heading 5&lt;/h5&gt;
        ///
        ///    &lt;em&gt;Italic&lt;/em&gt; &lt;span style=&quot;font-style: oblique&quot;&gt; Span&lt;/span&gt; &lt;br /&gt;
        ///    &lt;span style=&quot;font-variant: small-caps&quot;&gt; Small caps&lt;/span&gt;&lt;br /&gt;
        ///    &lt;strike&gt;Strike&lt;/strike&gt; &lt;span style=&quot;text-decoration: line-through&quot;&gt; Line Through&lt;/span&gt; &lt;span style=&quot;text-decoration: overl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompleteRunTest {
            get {
                return ResourceManager.GetString("CompleteRunTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;ul&gt;
        ///      &lt;li&gt;Coffee&lt;/li&gt;
        ///      &lt;li&gt;Tea&lt;/li&gt;
        ///      &lt;li&gt;Milk&lt;/li&gt;
        ///    &lt;/ul&gt;
        ///
        ///&lt;!--&lt;br class=&quot;ibp-rteFontSize-5&quot;/&gt;&lt;span style=&quot;font-size: 16px&quot;&gt;My Text &lt;/span&gt;&lt;/div&gt;
        ///
        ///&lt;table class=&quot;Standard_Table&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///&lt;thead&gt;
        ///    &lt;tr style=&quot;font-weight: bold;&quot;&gt;
        ///    &lt;td style=&quot;width: 16%; background-color: #ffff99;&quot;&gt;Column 1&lt;/td&gt;
        ///    &lt;td style=&quot;width: 16%; background-color: #ffff99;&quot;&gt;Column 2&lt;/td&gt;
        ///    &lt;td style=&quot;width: 16%; background-color: #ffff99;&quot;&gt;Column 3&lt;/td&gt;
        ///    &lt;td style=&quot;wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style type=&quot;text/css&quot; media=&quot;screen,print&quot;&gt;
        ///        .divPageBreak
        ///        {
        ///            page-break-after: always;
        ///            display: block;
        ///            clear: both;
        ///        }
        ///        table, td
        ///        {
        ///            border: 1px solid black;
        ///            border-collapse: collapse;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;divPageBreak&quot;&gt;
        ///        &lt;p class=&quot;Paragraph&quot; style=&quot;margin: 0cm 0cm 10pt;&quot;&gt;
        ///            &lt;span lang=&quot;EN-US&quot; style=&quot;font-size: 10pt; font-fami [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Demo2 {
            get {
                return ResourceManager.GetString("Demo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ol&gt;
        ///    &lt;li&gt;1&lt;/li&gt;
        ///    &lt;li&gt;2
        ///        &lt;ol&gt;
        ///            &lt;li&gt;3&lt;/li&gt;
        ///        &lt;/ol&gt;
        ///    &lt;/li&gt;
        ///    &lt;li&gt;4&lt;ol&gt;
        ///        &lt;li&gt;5&lt;ol&gt;
        ///            &lt;li&gt;6&lt;/li&gt;
        ///            &lt;li&gt;7&lt;/li&gt;
        ///        &lt;/ol&gt;
        ///        &lt;/li&gt;
        ///    &lt;/ol&gt;
        ///    &lt;/li&gt;
        ///&lt;/ol&gt;
        ///&lt;ol&gt;
        ///    &lt;li&gt;Asd&lt;/li&gt;
        ///    &lt;li&gt;Asd&lt;/li&gt;
        ///    &lt;li&gt;Asd
        ///        &lt;ol style=&quot;list-style-type: lower-alpha&quot;&gt;
        ///            &lt;li&gt;Asd&lt;/li&gt;
        ///            &lt;li&gt;Asd&lt;/li&gt;
        ///            &lt;li&gt;Asd
        ///                &lt;ol style=&quot;list-style-type: lower-roman&quot;&gt;
        ///                    &lt;li&gt;As&lt;/li&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NumberingList {
            get {
                return ResourceManager.GetString("NumberingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table align=&quot;center&quot; border=&quot;1&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td align=&quot;center&quot; style=&quot;background-color: rgb(135,206,235);&quot; colspan=&quot;2&quot;&gt;&lt;strong&gt;&lt;span style=&quot;font-size: 13px; font-family: tahoma;&quot;&gt;Change Type&lt;/span&gt;&lt;/strong&gt;&lt;/td&gt;
        ///            &lt;td align=&quot;center&quot; style=&quot;background-color: rgb(135,206,235);&quot;&gt;&lt;strong&gt;&lt;span style=&quot;font-size: 13px; font-family: tahoma;&quot;&gt;Change Risk&lt;/span&gt;&lt;/strong&gt;&lt;/td&gt;
        ///            &lt;td align=&quot;center&quot; style=&quot;background-color: rgb(135,206,235);&quot;&gt;&lt;strong&gt;&lt;span style=&quot;font [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RowSpan {
            get {
                return ResourceManager.GetString("RowSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;table&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;&amp;nbsp;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;/tbody&gt;
        ///&lt;/table&gt;
        ///
        ///&lt;table width=&quot;50%&quot; align=&quot;center&quot; border=&quot;1&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td ROWSPAN=2&gt;a1&lt;/td&gt;
        ///        &lt;td COLSPAN=&quot;2&quot;&gt;a23&lt;/td&gt;
        ///        &lt;td ROWSPAN=2&gt;a4&lt;/td&gt;
        ///        &lt;td COLSPAN=&quot;2&quot;&gt;a56&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///        &lt;td&gt;b2&lt;/td&gt;
        ///        &lt;td&gt;b3&lt;/td&gt;
        ///        &lt;td&gt;b5&lt;/td&gt;
        ///        &lt;td&gt;b6&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///        &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableRowSpan {
            get {
                return ResourceManager.GetString("TableRowSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] template {
            get {
                object obj = ResourceManager.GetObject("template", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
