//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesFor.HtmlToOpenXml {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PredefinedStyles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PredefinedStyles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotesFor.HtmlToOpenXml.Properties.PredefinedStyles", typeof(PredefinedStyles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:rPr xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;&lt;w:b /&gt;&lt;w:bCs /&gt;&lt;w:color w:val=&quot;4F81BD&quot; w:themeColor=&quot;accent1&quot; /&gt;&lt;w:sz w:val=&quot;18&quot; /&gt;&lt;w:szCs w:val=&quot;18&quot; /&gt;&lt;/w:rPr&gt;.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:rPr xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///    &lt;w:rFonts w:asciiTheme=&quot;majorHAnsi&quot; w:hAnsiTheme=&quot;majorHAnsi&quot; w:eastAsiaTheme=&quot;majorEastAsia&quot; w:cstheme=&quot;majorBidi&quot; /&gt;
        ///    &lt;w:b /&gt;
        ///    &lt;w:bCs /&gt;
        ///    &lt;w:color w:val=&quot;365F91&quot; w:themeColor=&quot;accent1&quot; w:themeShade=&quot;BF&quot; /&gt;
        ///    &lt;w:sz w:val=&quot;28&quot; /&gt;
        ///    &lt;w:szCs w:val=&quot;28&quot; /&gt;
        ///  &lt;/w:rPr&gt;.
        /// </summary>
        internal static string Heading_1 {
            get {
                return ResourceManager.GetString("Heading 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:rPr xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///    &lt;w:rFonts w:asciiTheme=&quot;majorHAnsi&quot; w:hAnsiTheme=&quot;majorHAnsi&quot; w:eastAsiaTheme=&quot;majorEastAsia&quot; w:cstheme=&quot;majorBidi&quot; /&gt;
        ///    &lt;w:b /&gt;
        ///    &lt;w:bCs /&gt;
        ///    &lt;w:color w:val=&quot;4F81BD&quot; w:themeColor=&quot;accent1&quot; /&gt;
        ///    &lt;w:sz w:val=&quot;26&quot; /&gt;
        ///    &lt;w:szCs w:val=&quot;26&quot; /&gt;
        ///  &lt;/w:rPr&gt;.
        /// </summary>
        internal static string Heading_2 {
            get {
                return ResourceManager.GetString("Heading 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:rPr xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///    &lt;w:rFonts w:asciiTheme=&quot;majorHAnsi&quot; w:hAnsiTheme=&quot;majorHAnsi&quot; w:eastAsiaTheme=&quot;majorEastAsia&quot; w:cstheme=&quot;majorBidi&quot; /&gt;
        ///    &lt;w:b /&gt;
        ///    &lt;w:bCs /&gt;
        ///    &lt;w:color w:val=&quot;4F81BD&quot; w:themeColor=&quot;accent1&quot; /&gt;
        ///  &lt;/w:rPr&gt;.
        /// </summary>
        internal static string Heading_3 {
            get {
                return ResourceManager.GetString("Heading 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:rPr xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///    &lt;w:rFonts w:asciiTheme=&quot;majorHAnsi&quot; w:hAnsiTheme=&quot;majorHAnsi&quot; w:eastAsiaTheme=&quot;majorEastAsia&quot; w:cstheme=&quot;majorBidi&quot; /&gt;
        ///    &lt;w:b /&gt;
        ///    &lt;w:bCs /&gt;
        ///    &lt;w:i /&gt;
        ///    &lt;w:iCs /&gt;
        ///    &lt;w:color w:val=&quot;4F81BD&quot; w:themeColor=&quot;accent1&quot; /&gt;
        ///  &lt;/w:rPr&gt;.
        /// </summary>
        internal static string Heading_4 {
            get {
                return ResourceManager.GetString("Heading 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:rPr xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///    &lt;w:rFonts w:asciiTheme=&quot;majorHAnsi&quot; w:hAnsiTheme=&quot;majorHAnsi&quot; w:eastAsiaTheme=&quot;majorEastAsia&quot; w:cstheme=&quot;majorBidi&quot; /&gt;
        ///    &lt;w:color w:val=&quot;243F60&quot; w:themeColor=&quot;accent1&quot; w:themeShade=&quot;7F&quot; /&gt;
        ///  &lt;/w:rPr&gt;.
        /// </summary>
        internal static string Heading_5 {
            get {
                return ResourceManager.GetString("Heading 5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:rPr xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///    &lt;w:rFonts w:asciiTheme=&quot;majorHAnsi&quot; w:hAnsiTheme=&quot;majorHAnsi&quot; w:eastAsiaTheme=&quot;majorEastAsia&quot; w:cstheme=&quot;majorBidi&quot; /&gt;
        ///    &lt;w:i /&gt;
        ///    &lt;w:iCs /&gt;
        ///    &lt;w:color w:val=&quot;243F60&quot; w:themeColor=&quot;accent1&quot; w:themeShade=&quot;7F&quot; /&gt;
        ///  &lt;/w:rPr&gt;.
        /// </summary>
        internal static string Heading_6 {
            get {
                return ResourceManager.GetString("Heading 6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:rPr xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;&lt;w:color w:val=&quot;0000FF&quot; w:themeColor=&quot;hyperlink&quot; /&gt;&lt;w:u w:val=&quot;single&quot; /&gt;&lt;/w:rPr&gt;.
        /// </summary>
        internal static string HyperLink {
            get {
                return ResourceManager.GetString("HyperLink", resourceCulture);
            }
        }
    }
}
