# This workflow will build, pack and deploy the solution on Nuget

name: 'publish_nuget.yml'

on:
  push:
    tags:
      - '[0-9]+.[0-9]+'
    branches:
      - master

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/') && github.ref_type == 'tag' && github.ref_name != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure tag is on master
        run: |
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref_name }})
          if ! git merge-base --is-ancestor $TAG_COMMIT origin/master; then
            echo "Tag is not on master branch. Skipping publish."
            exit 1
          fi
      - name: Setup .NET 8.
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build
        run: dotnet build --configuration Release
      - name: Pack
        run: dotnet pack src/Html2OpenXml/HtmlToOpenXml.csproj --configuration Release --output ./nupkg
      - name: Push nuget to NuGet.org
        run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      - name: Create Release and Upload Artifact to Release
        run: gh release create ${{github.ref_name}} -t "Release ${{github.ref_name}}" *.nupkg --generate-notes --draft
